### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by sachin0606** [akash-pal/Cordova-PouchDb-Cloudant#1] opened 2017-03-13 04:40 UTC
i downloaded the app and created the same database in cloudant but its giving 401 error,

any configuration i have to do? or just need to pass username and pasword in URL. 

and my app needs offline sync which i am trying to achieve , you have any opinion can you suggest me 

thanks !

Update: need to provide access to All domains in Cors [cloudant.com -> Account -> CORS].

**Comment by akash-pal** [comment] 2017-03-15 08:26
Sorry for the delay, I see the issue is solved. So closing it.

**Closed as completed by akash-pal** 2017-03-15 08:26 UTC
